const planetsInfo = {
  Sun: {
    facts: ['The Sun is a massive ball of hot, glowing gas, primarily composed of hydrogen (about 74%) and helium (about 24%).',
    'It is the main source of energy for our solar system, generating light, heat, and other forms of radiation through the process of nuclear fusion.',
    'The Sun\'s surface has dark, cooler regions called sunspots, which are caused by strong magnetic activity.']
  },
  Mercury: {
    facts: ['Mercury is the closest planet to the Sun and experiences extreme temperature variations, ranging from scorching hot during the day to freezing cold at night.',
    'It has a very thin atmosphere, composed mainly of gases like helium and trace amounts of hydrogen, oxygen, and other elements.',
    'Mercury has a large iron core, making it the most metal-rich planet in the solar system.']
    },
  Venus: {
    facts: ['Venus is often referred to as Earth\'s "sister planet" due to its similar size, mass, and composition. However, it has a thick, toxic atmosphere that creates a runaway greenhouse effect, making it the hottest planet in our solar system.',
    'It rotates on its axis very slowly, taking longer to complete one rotation than it does to orbit the Sun, resulting in its backward (retrograde) rotation compared to other planets.',
    'Venus has a dense layer of clouds made up of sulfuric acid, which gives it a bright, reflective appearance in the sky.']
  },
  Moon: {
    facts: ['The Moon is Earth\'s only natural satellite and is the fifth-largest moon in the solar system.',
    'It has distinct phases due to its orbit around Earth, which cause different portions of the Moon to be illuminated by the Sun, resulting in the familiar cycle of the lunar phases.',
    'The Moon\'s gravitational pull on Earth is responsible for the tides, which occur as a result of the Moon\'s gravitational attraction affecting the Earth\'s oceans.']
  },
  Earth: {
    facts: ['Earth is often referred to as the "Blue Planet" because of its abundant water, which covers approximately 71% of its surface. This vast amount of water is one of the key factors that make Earth a habitable planet.',
    'It has a magnetic field generated by its iron core, which helps protect the planet from harmful solar radiation.',
    'Earth orbits around the Sun in a slightly elliptical path. This journey takes approximately 365.25 days. As Earth travels around the Sun, the distance between them varies slightly throughout the year, but it has a minimal impact on our seasons, with the tilt of its axis playing a more significant role.']
  },
  Mars: {
    facts: ['Mars is often called the "Red Planet" due to its reddish appearance, caused by iron oxide (rust) on its surface.',
    'It has the tallest volcano and the deepest, longest canyon in the solar system. Olympus Mons, the largest volcano, is about three times the height of Mount Everest, and Valles Marineris, the canyon, is several times longer and deeper than the Grand Canyon on Earth.',
    'Mars has polar ice caps composed of water ice and carbon dioxide ice, and scientists have found evidence of ancient riverbeds and the possibility of liquid water in the past.']
  },
  Jupiter: {
    facts:  ['Jupiter is the largest planet in our solar system, with a mass more than twice that of all the other planets combined.',
    'It has a strong magnetic field that generates intense radiation belts, making it a hazardous environment for spacecraft.',
    'Jupiter is known for its iconic Great Red Spot, a massive storm that has been raging for over 300 years and is larger than Earth.']
  },
  Saturn:{
    facts: ['Saturn is famous for its beautiful and prominent ring system, made up of countless particles of ice and rock ranging in size from dust grains to larger moonlets.',
    'It has the second-largest moon in the solar system, Titan, which has a thick atmosphere and contains lakes and rivers of liquid methane and ethane.',
    'Saturn is the least dense planet, and if placed in a giant bathtub, it would float due to its low density.']
  },
  Uranus: {
    facts: ['Uranus is an ice giant, composed mostly of hydrogen and helium, with an atmosphere that contains traces of methane, giving it a bluish-green color.',
    'Unlike other planets, Uranus rotates on its side, with its poles almost aligned with the plane of its orbit, likely due to a massive collision early in its history.',
    'It has a unique set of faint, narrow rings, which were discovered when Uranus passed in front of a star, causing the starlight to momentarily flicker.']
  },
  Neptune: {
    facts: ['Neptune is the farthest known planet from the Sun and is the fourth-largest planet by diameter.',
    'It has the strongest winds in the solar system, with speeds reaching up to 1,200 miles per hour (2,000 kilometers per hour).',
    'Neptune has a dynamic atmosphere, featuring prominent dark spots similar to Jupiter\'s storms, the most famous of which is the Great Dark Spot discovered by the Voyager 2 spacecraft in 1989.']
  }  
}

export {planetsInfo};